language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia  --color=yes build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: kBnnjB+2pnWqZyb8ZsfM/zVFzSv+Ps/VNd2rBBPnBy5vqFbl0DWUbfEVFTDswr4RAXeWPxw8+tVxYX94145XXTSuG0un75AClWWC/yIECCknXsECWqjR5L3W7t6Fo2zu4V5kkRw1aGKL+a8ca6WrZyHwyxfQ2PTWFP9vNZtbNR9XMEAZfJY3mQuYSGKbJbi1C0u/6LPgChgA8A4ovm6Fp87YQdonecxGYcgyLvh1ihPR2FFtdUIKaZed8QOzQIdDvqbrwLFSn68rPXZd5dgFz2ebJDP/MgOnlrlXuzsOm+yMpC+MipU36dYclNX05T00bRCDiXsW9s0lGuojBCBLjsMjJXJElnAeSlkrjLYEmZ0yyTl86NH/PIHGlqrKuVlrhmzrAmLiFcadb3PTyWuayk0UAESzX+VyRwpKr/dj+y3ogWXrmIB2mgnZd/+cKp4rgRCHNqibjWFPnHPMocobPSz4q377jRm8a79ttfonUpYVUVVzqmI5aEBH7bHSZDJ0V4qWINrU+2O0ao7r+wrMbRAz1B0Dsia157vwZ6b/Drb/TN/4bZ5YWykVbgpF8p4TK7XYU8it5/pF6i1KfTpgaUi+cO+Ls0soTRkbYZ/Y3QI38tIDCAl14ZX5n4QX13eG0CLXQQq95bGAIJZbayzaHXu1VDJKw5svRzxcZ9VRe1A=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: benlorenz/XML2Builder
    tags: true
